### ISSUE TITLE
Byggeløype for nye versjoner av stilark

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nlb-scss#1]
Det bør være enkelt å legge til nye stilark i bøkene våre.

Vi kan gjøre noe av dette i produksjonssystemet kanskje. Der kan vi muligens automatisk sette inn nye versjoner av stilarkene. Men ikke helt sikker.

Alternativt legge det inn i `distribution-prepare`:
- https://github.com/nlbdev/distribution-prepare/issues/11

**Comment by usama49** [comment]
vi kan sette inn i produksjonssystemet men ikke nå fordi i starten vi har plan for å rense Html file sammen med CSS. når vi er ferdig med alle HTML filer da er greit å sette automatisk.

**Comment by josteinaj** [comment]
Hvordan er rutinen nå? Stemmer dette? @GauteR 

1. endre *`.scss` lokalt
2. bygge ny `*.min.css` lokalt
3. commit + push begge filer
4. eventuelt tag committen

**Comment by josteinaj** [comment]
@GauteR jeg får ikke bygget lokalt. Den ser ut til å kreve Python 2, som ikke er med i nyere Ubuntu-installasjoner. Tror det er litt risky å installere pga avhengigheter også, så vil helst unngå det. Alternativet er Docker for å ikke røre resten av systemet.

Jeg ser at `/dist`-mappen også forsvant på et tidspunkt, så jeg kan ikke plukke derifra. Vil gjerne ha ikke-minified-versjon for å kunne sammenligne med nåværende versjon og finne endringer.

**Comment by GauteR** [comment]
@josteinaj skal funke å bygge nå.
