### ISSUE TITLE
Gjøre blockquote kursiv

### ISSUE THREAD

**Issue by GauteR** [nlbdev/nlb-scss#12]
...

**Comment by josteinaj** [comment]
Testet i `about:blank` for å se hva som skjer om man ikke definerer noen ting:

![Skjermdump fra 2020-01-28 10-00-32](https://user-images.githubusercontent.com/295481/73249465-3a3a3280-41b5-11ea-9a48-a9d0946304d4.png)

```html
<p>Dette er en p:
    <em>Dette er em.</em>
    <i>Dette er i.</i>
    <strong>Dette er strong.</strong>
    <b>Dette er b.</b>
</p>

<blockquote>Dette er en blockquote:
    <em>Dette er em.</em>
    <i>Dette er i.</i>
    <strong>Dette er strong.</strong>
    <b>Dette er b.</b>
</blockquote>
```

Blockquote bør i alle fall ha et innrykk. Jeg ser noen steder at det har en vertikal strek langs venstre side der det er innrykk også, sånn som Github gjør det. Eksempel her:

> Dette er en blockquote:
> _Dette er `_`._
> __Dette er `__`.__
> *Dette er `*`*
> **Dette er `**`.**

**Comment by josteinaj** [comment]
…hvis blockquote kursiveres så bør vel forresten `<em>` og `<i>` inni blockquote "av-kursiveres"?
