### ISSUE TITLE
Stilark nettleserbok e-bok skriftstørrelse for stort

### ISSUE THREAD

**Issue by espso** [nlbdev/nlb-scss#22]
For stor skriftstørrelse for sidetall og margtekst

![image](https://user-images.githubusercontent.com/36958078/90883850-dffdfa80-e3ae-11ea-867b-6eb1fe9ca248.png)

**Comment by josteinaj** [comment]
@espso @GauteR er denne fortsatt aktuell?

**Comment by GauteR** [comment]
Ikke så aktuelt for min del. Uansett er det @usama49 som har kontroll på CSS for nettleserbok, så kanskje bedre om han tar det (hvis det skal tas)?

**Comment by usama49** [comment]
Det står ikke side nå i nettleserbok. Kan lukkes.
