### ISSUE TITLE
CSS-klasse for lister uten merking eller med forhåndsmerking

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nlb-scss#3]
Dette tilsvarer DTBooks preformaterte lister (`<list type="pl">`) eller CSS `list-style-type: none;` i HTML.

I den nordiske migratoren er klassen `list-style-type-none` definert for dette.

Se også: nlbdev/nordic-epub3-dtbook-migrator#282

**Comment by GauteR** [comment]
Dekkes av #13
