### ISSUE TITLE
Legge til en "hidden-headline" i CSS

### ISSUE THREAD

**Issue by GauteR** [nlbdev/nlb-scss#7]
Legge til en "hidden-headline" i CSSen vår med "display: none;", eller lignende for alle formater?

**Comment by josteinaj** [comment]
Overskrifter med denne klassen vil brukes til å generere innholdsfortegnelse, nav.xhtml, ncc.html, og i produksjonslinjer der man trenger midlertidige overskrifter underveis i produksjonen, som f.eks. ved innlesing i Hindenburg.

**Comment by GauteR** [comment]
Lagt til på alle stilark.
